In [18]:
import numpy as np

file1 = open("smalldigits.csv")   
digit = np.zeros((8, 8))


#intilaising dictionarys 0-9
array_of_dicts = []
for i in range(10):
    dict={}
    # array_of_dicts.append(dict)
    for j in range (65):
        dict.update({j:[0,0]})
    
    array_of_dicts.append(dict)


        

# all=np.array([])

# for i in range (1795):
#     rat = file1.readline()
#     all=np.append(all,rat)
# print(all)
# np.random.shuffle(all)



count=[0,0,0,0,0,0,0,0,0,0]



#adding
for i in range(1437):
    words = file1.readline()
    values = words.split(',')
    #print(values)
    classNum1=values[len(values)-1]
    classNum=int(classNum1)

  
    


    for i in range(65):
        
        if classNum == 0:
            count[0]+=1

            if(values[i]=='0'):
                array_of_dicts[0][i][0]+=1
            else:
                array_of_dicts[0][i][1]+=1

            pass
        elif classNum == 1:
            # Case 1
            count[1]+=1
            if(values[i]=='0'):
                array_of_dicts[1][i][0]+=1
            else:
                array_of_dicts[1][i][1]+=1
            pass
        elif classNum == 2:
            # Case 2
            count[2]+=1
            if(values[i]=='0'):
                array_of_dicts[2][i][0]+=1
            else:
                array_of_dicts[2][i][1]+=1
            pass
        elif classNum == 3:
            count[3]+=1
            if(values[i]=='0'):
                array_of_dicts[3][i][0]+=1
            else:
                array_of_dicts[3][i][1]+=1
            # Case 3
            pass
        elif classNum == 4:
            count[4]+=1
            if(values[i]=='0'):
                array_of_dicts[4][i][0]+=1
            else:
                array_of_dicts[4][i][1]+=1
            # Case 4
            pass
        elif classNum == 5:
            count[5]+=1
            if(values[i]=='0'):
                array_of_dicts[5][i][0]+=1
            else:
                array_of_dicts[5][i][1]+=1
            # Case 5
            pass
        elif classNum == 6:
            count[6]+=1
            if(values[i]=='0'):
                array_of_dicts[6][i][0]+=1
            else:
                array_of_dicts[6][i][1]+=1
            # Case 6
            pass
        elif classNum == 7:
            count[7]+=1
            if(values[i]=='0'):
                array_of_dicts[7][i][0]+=1
            else:
                array_of_dicts[7][i][1]+=1
            # Case 7
            pass
        elif classNum == 8:
            # Case 8
            count[8]+=1
            if(values[i]=='0'):
                array_of_dicts[8][i][0]+=1
            else:
                array_of_dicts[8][i][1]+=1
            pass
        elif classNum == 9:
            # Case 9
            count[9]+=1
            if(values[i]=='0'):
                array_of_dicts[9][i][0]+=1
            else:
                array_of_dicts[9][i][1]+=1
            pass
        else:
            # Default Case
            pass
priori=[]

for i in range(10):
    count[i]=count[i]/65
    priori.append(count[i]/1437)
# print(count,priori)


# divinding by counter

for i in range(len(array_of_dicts)):
    for j in range (65):
        array_of_dicts[i][j][0]/=count[i]
        array_of_dicts[i][j][1]/=count[i]

# for i in range(len(array_of_dicts)):
#     print( array_of_dicts[i])

# print(" ")
        
#laplacing ( needs fixing)

for i in range(len(array_of_dicts)):
    for j in range (65):
        if array_of_dicts[i][j][0]==0:

            array_of_dicts[i][j][0]=(1)/(64+(2))
            array_of_dicts[i][j][1]=1-(1)/(64+(2))
        elif array_of_dicts[i][j][1]==0:
            array_of_dicts[i][j][1]=(1)/(64+(2))
            array_of_dicts[i][j][0]=1-(1)/(64+(2))
        

        
for i in range(len(array_of_dicts)):
    print( array_of_dicts[i])
        



















{0: [0.9848484848484849, 0.015151515151515152], 1: [0.9848484848484849, 0.015151515151515152], 2: [0.6223776223776224, 0.3776223776223776], 3: [0.015151515151515152, 0.9848484848484849], 4: [0.04195804195804196, 0.958041958041958], 5: [0.7062937062937062, 0.2937062937062937], 6: [0.9848484848484849, 0.015151515151515152], 7: [0.9848484848484849, 0.015151515151515152], 8: [0.9848484848484849, 0.015151515151515152], 9: [0.965034965034965, 0.03496503496503497], 10: [0.02097902097902098, 0.9790209790209791], 11: [0.006993006993006993, 0.993006993006993], 12: [0.06993006993006994, 0.9300699300699301], 13: [0.055944055944055944, 0.9440559440559441], 14: [0.9090909090909091, 0.09090909090909091], 15: [0.9848484848484849, 0.015151515151515152], 16: [0.9848484848484849, 0.015151515151515152], 17: [0.6293706293706294, 0.3706293706293706], 18: [0.006993006993006993, 0.993006993006993], 19: [0.5874125874125874, 0.4125874125874126], 20: [0.8181818181818182, 0.18181818181818182], 21: [0.055944055944

In [19]:
#Testing

#visualising number
def number(digit,values):
    countt=0
    for i in range(8):
        for j in range(8):
            
            digit[i, j] = int(values[countt])
            countt+=1
    print(digit)




countRight=0
countWrong=0

for i in range(1796):
   

    probArr=[] # P(input/class) (1010101.../0,1,...9), 
    
    finalProb=[] #P(class/input)
    classNum=0
    
    if i<1437:
        continue
    else:
        words = file1.readline()
        

        values=words.split(',')
        classNum=values[len(values)-1]  # actual number 
        values.pop(-1)# removing actulaay number form string


        #now we need to find probabilty of each 0-9
        for j in range(10):
            product=[]

            for i in range(len(values)):
                 
                if(values[i]=='0'):
                    product.append(array_of_dicts[j][i][0])
                else:
                     product.append(array_of_dicts[j][i][1])
            

            # probArr.append(product)
            # print(product)
            # print(len(product))

            #converting to log and then summing for underflow
            log_probabilities = np.log(product)
            log_sum = np.sum(log_probabilities)
            probArr.append(log_sum)

    print(probArr)
    counter=0

    for num in range(10):
        top=(probArr[num]*priori[num])
        bottom=0
        for den in range (10):
                bottom +=probArr[den]*priori[den]
           
        finalProb.append(top/bottom)
    print(finalProb)
    print("")
    # summer=0
    # for what in finalProb:
    #     summer+=what
    # print(summer)
   
    max_value = max(finalProb)
    out=finalProb.index(max_value)
    if(out==classNum):
        countRight+=1
    else:
        countWrong+=1
    
    print("predicted: "+ str(out))
    print("actual: "+str(classNum))
    print(" ")
    number(digit,values)

# print("right ")
# print(countRight)

[-68.15996191487258, -28.295415451836153, -13.199905191376889, -34.57827181477687, -61.88290904198611, -34.56854567182505, -44.62254797275149, -53.71791570678357, -28.414109806295, -41.7735011813134]
[0.16573017754721417, 0.07024333937031366, 0.031870976884199605, 0.08584052374345705, 0.15151981532419925, 0.0852285951886216, 0.1092579572097881, 0.13061450531134983, 0.06812231311917497, 0.10157179630168185]

predicted: 0
actual: 2

 
[[0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0.]]
[-53.959953899246926, -33.25330809866398, -25.91105450254812, -14.679633653965691, -50.3279567578068, -29.317629266354945, -41.729726834379385, -43.33864427727364, -27.93128332091733, -29.139585461911416]
[0.15369864473368966, 0.09670527017180983, 0.07328850502596675, 0.042690427500263625, 0.14435579463945103, 0.08467579475455395, 0.11969347188